apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-redis-app-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: simple-redis-app
  template:
    metadata:
      labels:
        app: simple-redis-app
    spec:
      containers:
        - name: simple-redis-app
          image: docker.io/fitzsimmonsjp/simple-redis-app:latest  # Replace with your Docker image path
          ports:
            - containerPort: 4052  # Replace with the port your Node.js app listens on
